Adding clear btn callback
ericgio/react-bootstrap-typeahead pull request #630
Opened 2021-03-28 00:33 UTC by anonymous-ME

**What issue does this pull request resolve?**
onInputChange not called when input cleared.

**What changes did you make?**
added the callBack

**Is there anything that requires more attention while reviewing?**
nope

2021-03-28 03:41 UTC, ericgio requested changes
Hey @anonymous-ME, thanks for submitting this PR. The issue you're trying to solve with this change is actually a bit more complicated than it first appears. `onInputChange` also passes the change event as the second argument, but that event doesn't actually happen, since the value changes in response to a click on a different element.

2021-03-28 03:41 UTC, ericgio commented on src/core/Typeahead.js
> +    props.onInputChange("");
As noted, `onInputChange` passes the change event as the second argument. It also doesn't seem like a good idea to trigger a callback during a state change. That should happen after the state change is complete.

2021-03-28 03:42 UTC, ericgio commented
Oh, and if you'd like to continue pursuing this change, some tests would be great :)

2021-03-28 14:41 UTC, anonymous-ME commented
> Hey @anonymous-ME, thanks for submitting this PR. The issue you're trying to solve with this change is actually a bit more complicated than it first appears. `onInputChange` also passes the change event as the second argument, but that event doesn't actually happen, since the value changes in response to a click on a different element.

Hi @ericgio, what solution would you suggest in this case?

2021-03-28 14:44 UTC, anonymous-ME commented
Should we add a callback for onClear instead?

2021-03-29 16:54 UTC, ericgio commented
I think the solution is that the event needs to be manually triggered by the clear callback, which would then trigger `onInputChange` as one would expect.

2021-03-31 10:12 UTC, anonymous-ME commented
Hi @ericgio, I'm thinking of doing something like this to simulate onChange for TypeaheadManager. 

```
  const event = new Event('change');
  element.dispatchEvent(event);
```

But not sure how to get TypeaheadManager element reference inside of clearTypeahead callback.

2021-08-15 07:32 UTC, ericgio commented
This was added in v5.2

2021-08-15 07:32 UTC, closed without merging